### ISSUE TITLE
Комментарий Шредингера

### ISSUE THREAD

**Issue by Orneliia** [GeorgeKontsevik/sloyka#30]
**Describe the bug**
После запуска парсинга, при открытие csv файла в Excel образуются строчки с кусочками потерянных фраз как из комментариев. В датафрейме данные кусочки отсуствуют.

**To Reproduce**
1. Использовать парсер для постов и комментариев (на примере для группы https://vk.com/siverskiy_life)
2. Сохранить полученные данные в формат csv
3. В Excel через кнопку "Получить данные" открыть полученный csv файл
4. Ура, вы добрались до строчек с кусочками потерянных фраз (скриншот 1)
5. Через пандас датафрейм потерявшейся кусочек не удается найти.

**Screenshots**
![image](https://github.com/GeorgeKontsevik/sloyka/assets/161454397/f88aef0d-7173-4802-9708-5c4f10272ab9)

**Comment by GeorgeKontsevik** [comment]
could reproduce the issue, havent faced it during testing on other groups
