### ISSUE TITLE
Geocoder. Problem with 'only_full_street_name' key in dataframe in get_stem stage.

### ISSUE THREAD

**Issue by LeonDeTur** [GeorgeKontsevik/sloyka#35]
**Describe the bug**
Geocoder felt again. Last version from dev. can't get stem in module, throws error.
**To Reproduce**
1. from sloyka import Geocoder
2. df = pd.read_csv(data)
3. g = Geocoder(osm_city_name='Колпино', osm_city_level=8)
4. gdf = g.run(df, 'text')

**Expected behavior**
Expected return geocoded data.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~\AppData\Local\pypoetry\Cache\virtualenvs\sloyka-C3DMZNjP-py3.11\Lib\site-packages\pandas\core\indexes\base.py:3802, in Index.get_loc(self, key, method, tolerance)
   3801 try:
-> 3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:

File ~\AppData\Local\pypoetry\Cache\virtualenvs\sloyka-C3DMZNjP-py3.11\Lib\site-packages\pandas\_libs\index.pyx:138, in pandas._libs.index.IndexEngine.get_loc()

File ~\AppData\Local\pypoetry\Cache\virtualenvs\sloyka-C3DMZNjP-py3.11\Lib\site-packages\pandas\_libs\index.pyx:165, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:5745, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:5753, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'only_full_street_name'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[3], line 3
      1 g = Geocoder(osm_city_name='Колпино', osm_city_level=8)
----> 3 gdf = g.run(df, 'text')

File ~\PycharmProjects\sloyka\sloyka\src\geocoder.py:754, in Geocoder.run(self, df, text_column)
    752 df = self.get_street(df, text_column)
    753 street_names = self.get_stem(street_names)
--> 754 df = self.find_word_form(df, street_names)
    755 gdf = self.create_gdf(df)
    756 # gdf2 = self.merge_to_initial_df(gdf, initial_df)
    757 
    758 # # Add a new 'level' column using the get_level function
    759 # gdf2["level"] = gdf2.progress_apply(self.get_level, axis=1)
    760 # gdf2 = self.set_global_repr_point(gdf2)

File ~\PycharmProjects\sloyka\sloyka\src\geocoder.py:563, in Geocoder.find_word_form(self, df, strts_df)
    560 # df.dropna(subset=["full_street_name", 'only_full_street_name'], inplace=True)
    562 df["location_options"] = df["full_street_name"].str.split(",")
--> 563 df["only_full_street_name"] = df["only_full_street_name"].str.split(",")
    566 tmp_df_1 = df["location_options"].explode()
    567 tmp_df_1.name = "addr_to_geocode"

File ~\AppData\Local\pypoetry\Cache\virtualenvs\sloyka-C3DMZNjP-py3.11\Lib\site-packages\pandas\core\frame.py:3807, in DataFrame.__getitem__(self, key)
   3805 if self.columns.nlevels > 1:
   3806     return self._getitem_multilevel(key)
-> 3807 indexer = self.columns.get_loc(key)
   3808 if is_integer(indexer):
   3809     indexer = [indexer]

File ~\AppData\Local\pypoetry\Cache\virtualenvs\sloyka-C3DMZNjP-py3.11\Lib\site-packages\pandas\core\indexes\base.py:3804, in Index.get_loc(self, key, method, tolerance)
   3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:
-> 3804     raise KeyError(key) from err
   3805 except TypeError:
   3806     # If we have a listlike key, _check_indexing_error will raise
   3807     #  InvalidIndexError. Otherwise we fall through and re-raise
   3808     #  the TypeError.
   3809     self._check_indexing_error(key)

KeyError: 'only_full_street_name'

data example:
[messages.csv](https://github.com/GeorgeKontsevik/sloyka/files/15360893/messages.csv)

screenshots:
![image](https://github.com/GeorgeKontsevik/sloyka/assets/100690100/41a77e6d-a6d4-4974-a00f-90f3c1133155)
![image](https://github.com/GeorgeKontsevik/sloyka/assets/100690100/ac9326d1-d841-4d24-afef-d1492a866985)

**Comment by GeorgeKontsevik** [comment]
thanks I will check it out in a few days

**Comment by GeorgeKontsevik** [comment]
fixed
