### ISSUE TITLE
Data loss after using geocoder

### ISSUE THREAD

**Issue by LeonDeTur** [GeorgeKontsevik/sloyka#40]
**Describe the bug**
Input of 60 rows in geocoder, output 15.

**To Reproduce**
go to branch feat/group_names
run
gdf = g.run(osm_id = 338635, tags = {"admin_level": ["8"]}, date = "2024-04-22T00:00:00Z", df=df, text_column='text')

**Expected behavior**
gdf with all input rows

***data***
[messages.csv](https://github.com/user-attachments/files/15523460/messages.csv)

**Desktop (please comple4te the following information):**
- Windows 11
- Python 3.11.8

**Comment by Voronapxl** [comment]
Добавил логгер инфо. Походу, надо будет Глебу писать

`2024-06-08 22:27:54,957 SequenceTagger predicts: Dictionary with 5 tags: O, S-ADDRESS, B-ADDRESS, E-ADDRESS, I-ADDRESS
**06-08 22:27 | INFO     | Initial number of rows: 73**
Processing category admin_level: 100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
06-08 22:27 | ERROR    | Error fetching timestamp for osmid 1040824844
Traceback (most recent call last):

  File "[C:\Users\trolo\python3.10.9\lib\](file:///C:/Users/trolo/python3.10.9/lib/)runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x0000028256600DF0, file "c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\ipykernel_launc...
           └ <function _run_code at 0x00000282566215A0>

  File "[C:\Users\trolo\python3.10.9\lib\](file:///C:/Users/trolo/python3.10.9/lib/)runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x0000028256600DF0, file "c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\ipykernel_launc...

  File "[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/)ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from 'c:\\Users\\trolo\\python3.10.9\\envs\\nirmapy\\lib\\site-packages\\ipykernel\\kernelapp.py'>

  File "[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\traitlets\config\](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/traitlets/config/)application.py", line 1075, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x000002825A94ADD0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x00000282561B8700>

  File "[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\ipykernel\](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/ipykernel/)kernelapp.py", line 739, in start
...
osmapi.errors.ElementNotFoundApiError: Request failed: 404 - Not Found - b''
**06-08 22:27 | INFO     | Number of rows after matching group to area: 73
06-08 22:27 | INFO     | Number of rows after preprocessing text column: 73**
06-08 22:27 | INFO     | run_OSM_dfs started
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?384bc5dc-3e78-4e79-bb6a-c2b40843efac) or open in a [text editor](command:workbench.action.openLargeOutput?384bc5dc-3e78-4e79-bb6a-c2b40843efac). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
[c:\Users\trolo\CodeNIRMA\sloyka\sloyka\src\geocoder.py:318](file:///C:/Users/trolo/CodeNIRMA/sloyka/sloyka/src/geocoder.py:318): UserWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in a future release.
  green_obj = ox.geometries_from_place(osm_city_name, tags)
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\algorithms.py:522](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/algorithms.py:522): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
[c:\Users\trolo\CodeNIRMA\sloyka\sloyka\src\geocoder.py:330](file:///C:/Users/trolo/CodeNIRMA/sloyka/sloyka/src/geocoder.py:330): UserWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in a future release.
  osm_num_obj = ox.geometries_from_place(osm_city_name, tags)
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
...
  return np.find_common_type(types, [])
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?5e466c7e-d19b-4485-bfb2-49e1fae4e0df) or open in a [text editor](command:workbench.action.openLargeOutput?5e466c7e-d19b-4485-bfb2-49e1fae4e0df). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
06-08 22:28 | INFO     | find_other_geo_obj started
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\algorithms.py:522](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/algorithms.py:522): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
06-08 22:28 | INFO     | Number of rows after get_other_geo_objects: 0
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\algorithms.py:522](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/algorithms.py:522): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\algorithms.py:522](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/algorithms.py:522): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
06-08 22:28 | INFO     | clear_names started
06-08 22:28 | INFO     | Number of rows in street_names: 3302
06-08 22:28 | INFO     | get_street started
06-08 22:28 | INFO     | extract_ner_street started
 33%|███▎      | 24/73 [00:00<00:00, 118.30it/s]
2024-06-08 22:28:40,867 Warning: An empty Sentence was created! Are there empty strings in your dataset?
**100%|██████████| 73/73 [00:00<00:00, 153.38it/s]
100%|██████████| 73/73 [00:00<00:00, 241.72it/s]**
06-08 22:28 | INFO     | pattern1.sub started

100%|██████████| 9/9 [00:00<00:00, 9013.55it/s]
06-08 22:28 | INFO     | pattern2.findall started

100%|██████████| 9/9 [00:00<?, ?it/s]
06-08 22:28 | INFO     | pattern2.sub started

100%|██████████| 9/9 [00:00<00:00, 9017.85it/s]
06-08 22:28 | INFO     | extract_building_num started

  0%|          | 0/9 [00:00<?, ?it/s]c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
100%|██████████| 9/9 [00:00<00:00, 9004.95it/s]
06-08 22:28 | INFO     | extract_toponym started

  0%|          | 0/9 [00:00<?, ?it/s]c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
100%|██████████| 9/9 [00:00<00:00, 900.13it/s]
06-08 22:28 | INFO     | get_stem started

**06-08 22:28 | INFO     | Number of rows after find_word_form: 15**
06-08 22:28 | INFO     | create_gdf started
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\pandas\core\dtypes\cast.py:1641](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/pandas/core/dtypes/cast.py:1641): DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
100%|██████████| 15/15 [00:03<00:00,  4.73it/s]
**06-08 22:28 | INFO     | Number of rows after find_word_form create_gdf: 15
06-08 22:28 | INFO     | Number of rows in final GeoDataFrame: 15
06-08 22:28 | INFO     | Number of rows after geo_obj_tag: 15**

[c:\Users\trolo\python3.10.9\envs\nirmapy\lib\site-packages\geopandas\array.py:1406](file:///C:/Users/trolo/python3.10.9/envs/nirmapy/lib/site-packages/geopandas/array.py:1406): UserWarning: CRS not set for some of the concatenation inputs. Setting output's CRS as WGS 84 (the single non-null crs provided).
  warnings.warn(`

**Comment by GeorgeKontsevik** [comment]
fixed
